site_name: Mcorne documentation
theme:
  name: material
  logo: Mcorne_02_pure.png
  palette:
   primary: black
   accent: deep purple
   scheme: slate
   features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
